### ISSUE TITLE
Configuration difficulties

### ISSUE THREAD

**Issue by fmottaz** [vrkttr/homebridge-vicare#2]
Hi, i just found and installed your plug-in. Went through the config steps but the plug in does not run. I see the following:
a.
If I try to display the plugin log, I have a message which says it could not find the plugin alias.
b.
In the General log i get this:
[6/30/2024, 7:06:35 PM] [ViCareThermostat] Using redirect URI: http://192.168.132.2:4200
[6/30/2024, 7:06:35 PM] [ViCareThermostat] Opening browser for authentication: https://iam.viessmann.com/idp/v3/authorize?client_id=7f4315703cb948055a1ee35e8c555f54&redirect_uri=http%3A%2F%2F192.168.132.2%3A4200&scope=IoT%20User&response_type=code&code_challenge_method=S256&code_challenge=CyxmDCXLL3_Jx9uPhEHFA4uLfDk96gv9v6zW5AvY1tQ
[6/30/2024, 7:06:35 PM] [ViCareThermostat] Server is listening on 192.168.132.2:4200
c.
If I follow the URL, i get this: {"error":"invalid_request", "error_description":"Invalid redirection URI."}

So, I’m stuck here. Thanks

**Comment by Kar0ll0** [comment]
In this link there is an error. It should be redirect_url but instead it is redirect_uri. But still after you login you get authentication error. Is there anyway that you can help with this problem @vrkttr?


Here is the correct URL:

https://iam.viessmann.com/idp/v3/authorize?client_id=7f4315703cb948055a1ee35e8c555f54&redirect_url=http%3A%2F%2F192.168.132.2%3A4200&scope=IoT%20User&response_type=code&code_challenge_method=S256&code_challenge=CyxmDCXLL3_Jx9uPhEHFA4uLfDk96gv9v6zW5AvY1tQ

**Comment by fmottaz** [comment]
I tried with the modified URL proposed by @Kar0ll0 but get authentication error as well. Not sure why this issue has been closed.

**Comment by amactus** [comment]
Hi, I am also facing this authentication error issue, even after ensuring I'm up to date and following the changes noted above. @fmottaz @vrkttr have either of you had luck solving this issue?

**Comment by fmottaz** [comment]
﻿Hi, no, unfortunately.Envoyé de mon iPadLe 14 sept. 2024 à 22:39, Pablo ***@***.***> a écrit :﻿
Hi, I am also facing this authentication error issue, even after ensuring I'm up to date and following the changes noted above. @fmottaz @vrkttr have either of you had luck solving this issue?
